# Generated by Django 5.1.1 on 2024-10-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='telefones',
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='telefone',
            new_name='telefones',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='telefone',
            new_name='telefones',
        ),
    ]
