# Generated by Django 5.1.1 on 2024-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_funcionario_nascimento_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nascimento',
            field=models.DateField(null=True),
        ),
    ]
