# Generated by Django 5.1.1 on 2024-10-11 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_alter_cliente_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefones',
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.telefone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones_cliente', to='servicos.cliente')),
            ],
            options={
                'verbose_name': 'Telefone Cliente',
                'verbose_name_plural': 'Telefones Cliente',
            },
            bases=('servicos.telefone',),
        ),
    ]
