# Generated by Django 5.1.1 on 2024-10-11 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0007_remove_cliente_telefones_telefonecliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='telefones',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TelefoneEmpresa',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.telefone')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones_empresa', to='servicos.empresa')),
            ],
            options={
                'verbose_name': 'Telefone Empresa',
                'verbose_name_plural': 'Telefones Empresa',
            },
            bases=('servicos.telefone',),
        ),
    ]
