# Generated by Django 5.1.1 on 2024-10-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0009_remove_fornecedor_telefones_telefonefornecedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='telefones',
        ),
        migrations.CreateModel(
            name='TelefoneFuncionario',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicos.telefone')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones_funcionario', to='servicos.funcionario')),
            ],
            options={
                'verbose_name': 'Telefone Funcionario',
                'verbose_name_plural': 'Telefones Funcionario',
            },
            bases=('servicos.telefone',),
        ),
    ]
