# Generated by Django 5.1.1 on 2024-10-11 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('servicos', '0010_remove_funcionario_telefones_telefonefuncionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemordemservico',
            name='ordem_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.ordemservico'),
        ),
    ]
