# Generated by Django 5.1.1 on 2024-10-12 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciador_base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gerenciador_base_app.endereco')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='TelefoneCliente',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciador_base_app.telefone')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones_cliente', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Telefone Cliente',
                'verbose_name_plural': 'Telefones Cliente',
            },
            bases=('gerenciador_base_app.telefone',),
        ),
    ]
