# Generated by Django 5.1.1 on 2024-10-12 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerenciador_base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='EnderecoEmpresa',
            fields=[
                ('endereco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciador_base_app.endereco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos_empresa', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Endereço Empresa',
                'verbose_name_plural': 'Endereços Empresas',
            },
            bases=('gerenciador_base_app.endereco',),
        ),
        migrations.CreateModel(
            name='TelefoneEmpresa',
            fields=[
                ('telefone_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gerenciador_base_app.telefone')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones_empresa', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Telefone Empresa',
                'verbose_name_plural': 'Telefones Empresas',
            },
            bases=('gerenciador_base_app.telefone',),
        ),
    ]
